focal_length: 6 # in mm

# the following two fields are from manufactory
# reference: https://www.ptgrey.com/blackfly-32-mp-color-gige-poe-sony-imx265-2
# do NOT change unless necessary
pixel_size: 3.0e-3      # in mm
film_shape: [1980, 1080] # in pixel