################################### Developer use only ##############################
threshold: 
  min_pin_difference: 0.2        ### Minimum rate(%) of change in the pin translation of the pattern
  min_area_scale: 0.4             ### Minimum rate(%) of change in the x-direction position of the pattern
  min_area_difference: 0.008      ### Minimum rate(%) of change in the area of pattern
  min_rotation_difference: 0.18     ### Minimum rate(%) of change in the rotation of pattern
  min_pattern_sharpness: 0.25      ### Minimum of sharpness allowed of the pattern
  max_pattern_moving_speed: 5.0   ### Maximum of movement speed allowed of the pattern
  max_skew_limit: 0.35
  lambda: 1e-8
  batch_size: 50

base:
  is_using_cv4: False             ### whether use opencv4 to detect corners
  is_using_OR_calibrate: False     ### whether use the Object release method to calibrate
  sum_images_need: 50             ### Number of images required
  img_block_shape: (2, 3)
  block_img_need: 5.5        ### NUmber of each image block required at the beginning 
  max_iter: 4                    ###

RLS: # while preform RLS regulation for each camera
  4mm: False
  6mm: False
  12mm: False
  25mm: False

debug:
  viz: False
  save: False
  verbose: False
###################################################################################




#################################### User input ######################################
camera:
  img_shape: [1024, 576]
  is_cam390: False
  output_img_shape: [1024, 576]
  id: 4
  flip_input_img: False           # *must, true only if the input images is vertically captured, e.g. for rear cameras.
  flip_output_img: False          # *must, set true for horizontally calibrated camera but will be vertically installed.
                                  #   e.g rear cams
  ## please check the following usage to set params above ##
  # capture horizontally, use horizontally: flip_input_img = False, flip_output_img = False
  # capture horizontally, use vertically: flip_input_img = False, flip_output_img = True
  # capture vertically, use horizontally: flip_input_img = True, flip_output_img = False
  # capture vertically, use vertically: flip_input_img = True, flip_output_img = True 

data:
  input_method: topic         # dataset or topic
  dataset_name: 2019-08-13-13-37-55 
  output_dir: /root/.tspkg/share/cam_intrinsic_calibrator/results/ #/root/.tspkg/share/cam_intrinsic_calibrator/results/  
                                                                    #/mnt/truenas/scratch/lingbo.yu/cam_intrinsic_results/
                                                                    
  num_thread: 6

pattern:
  is_ring: False
  pattern_shape: (8, 11)
  corner_distance: 50
################################################################################