focal_length: 5.07 # in mm

# the following two fields are from manufactory
# reference: https://www.ptgrey.com/blackfly-32-mp-color-gige-poe-sony-imx265-2
# do NOT change unless necessary
pixel_size: 2.1e-3      # in mm
fov: 121                 # in degree
film_shape: [3840, 2160] # in pixel
undistort_shape: [7200, 2400]